#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
    NRNHOME="/home/adin726/neuron/nrn"
fi
if test "${NEURONHOME}" = "" ; then
    NEURONHOME=${NRNHOME}/share/nrn
    export NEURONHOME
fi
if test "x${NRNBIN}" = "x" ; then
    NRNBIN="/home/adin726/neuron/nrn/x86_64/bin"
fi
if test "" = "yes" ; then
    NRNIV="${NRNBIN}/nrniv.app/Contents/MacOS/nrniv"
else
    NRNIV="${NRNBIN}/nrniv"
fi
"${NRNIV}" -dll "/home/adin726/paper-dist/FR_distribution/biophys_components/mechanisms/x86_64/.libs/libnrnmech.so" "$@"
